Repository openvinotoolkit/workbench, pull requests merged in 2022-12, with the labels that each got.

#126 [97793] Download the OV package in notebook instead of a Docker image
  docker/dockerfiles/Dockerfile
  docker/dockerfiles/Dockerfile_opensource_image.template
  docker/local/build_image.sh
  requirements/requirements_jupyter.txt
  tests/jupyter_tests/execute_notebooks_from_bom.sh
  tutorials/sample_application/tutorial_sample_application.ipynb
Labels: bug, dependencies, docker

#129 [98990] Unskip tests for generated Jupyter notebooks
  tests/jupyter_tests/execute_notebooks_from_bom.sh
  wb/main/jupyter_notebooks/cell_templates/profiling_code_cell.jinja
Labels: CI, to-be-merged

#128 [95476] Update certify and notebook dependencies
  requirements/requirements_jupyter.txt
Labels: dependencies, to-be-merged, SDL

#131 [DOCS] Change links to optimization guide
  docs/Workbench_DG/Int-8_Quantization.md
  docs/Workbench_DG/Run_Inference.md
Labels: documentation

#130 [95476] Update gunicorn and eventlet
  requirements/requirements.txt
Labels: dependencies, SDL
