Repository openvinotoolkit/workbench, pull requests merged in 2022-03, with the labels that each got.

#12 [69768] Make scripts executable
  automation/bom/copy_by_bom.sh
  automation/bootstrap/bootstrap_git_hooks.sh
  automation/bootstrap/bootstrap_os.sh
  automation/bootstrap/bootstrap_repository.sh
  automation/bootstrap/bootstrap_variables.sh
  automation/bootstrap/install_client_dependencies.sh
  automation/bootstrap/install_docker_packages.sh
  automation/bootstrap/install_python_packages.sh
  client/automation/Jenkins_scripts/run_bom_test.sh
  client/automation/Jenkins_scripts/run_lint.sh
  client/automation/Jenkins_scripts/run_npm_audit.sh
  client/automation/Jenkins_scripts/run_unittests.sh
  client/automation/dc_dev_config/entrypoint.sh
  docker/bootstrap/docker-entrypoint.sh
  docker/dc_dev_config/nginx/entrypoint.sh
  docker/dc_dev_config/server/entrypoint.sh
  docker/remote_execution_docker/run.sh
  docker/scripts/configure_ov_notebooks_env.sh
  docker/scripts/docker-entrypoint.sh
  docker/scripts/start_jupyter.sh
  docker/scripts/start_nginx.sh
  docker/scripts/start_postgresql.sh
  docker/scripts/start_rabbitmq.sh
  docker/scripts/update_OMZ.sh
  docker/scripts/wait_until_db_is_live.sh
  scripts/linux/install_dependencies.sh
  scripts/mac/install_dependencies.sh
  tests/benchmark_performance_tests/collect_cli_benchmark_results.sh
  tests/benchmark_performance_tests/run_performance_test_with_docker.sh
  tests/deployment_tests/scripts/copy_and_make_sample.sh
  tests/deployment_tests/scripts/execute_sample.sh
  tests/jupyter_tests/execute_generated_notebooks.sh
  tests/jupyter_tests/execute_notebooks_from_bom.sh
  wb/main/scripts/check_passwordless_sudo.sh
  wb/main/scripts/is_supported_os.sh
  wb/main/scripts/is_supported_pip_version.sh
  wb/main/scripts/is_supported_python_version.sh
Labels: bug

#13 [81845] Erase Environments files
  wb/main/api_endpoints/v1/registry.py
Labels: bug, to-be-merged

#28 [82172] Fix model zoo data source
  .pre-commit-config.yaml
  client/package-lock.json
  client/package.json
  client/src/app/modules/model-manager/components/hugging-face-import-ribbon-content/hugging-face-import-ribbon-content.component.html
  client/src/app/modules/model-manager/components/hugging-face-import-ribbon-content/hugging-face-import-ribbon-content.component.ts
  client/src/app/modules/model-manager/components/hugging-face-import-ribbon-content/huggingface-model-details/huggingface-model-details.component.html
  client/src/app/modules/model-manager/components/hugging-face-import-ribbon-content/huggingface-model-details/huggingface-model-details.component.scss
  client/src/app/modules/model-manager/components/hugging-face-import-ribbon-content/huggingface-model-details/huggingface-model-details.component.spec.ts
  client/src/app/modules/model-manager/components/hugging-face-import-ribbon-content/huggingface-model-details/huggingface-model-details.component.ts
  client/src/app/modules/model-manager/components/hugging-face-import-ribbon-content/huggingface-model-details/markdown/index.ts
  client/src/app/modules/model-manager/components/hugging-face-import-ribbon-content/huggingface-model-details/markdown/markdown.scss
  client/src/app/modules/model-manager/components/hugging-face-import-ribbon-content/huggingface-model-details/markdown/markdown.service.spec.ts
  client/src/app/modules/model-manager/components/hugging-face-import-ribbon-content/huggingface-model-details/markdown/markdown.service.ts
  client/src/app/modules/model-manager/components/hugging-face-import-ribbon-content/huggingface-model-details/markdown/markdown.ts
  client/src/app/modules/model-manager/components/model-zoo-layout/model-zoo-details/model-zoo-details.component.scss
  client/src/app/modules/model-manager/components/model-zoo-layout/model-zoo-layout.component.scss
  client/src/app/modules/model-manager/model-manager.module.ts
  client/src/app/shared/models/model-zoo-data-source/base-model-zoo-data-source.ts
  client/src/app/shared/models/model-zoo-data-source/huggingface-model-zoo-data-source.ts
  client/src/app/shared/models/model-zoo-data-source/open-model-zoo-data-source.ts
  client/src/styles.scss
Labels: enhancement, blocked

#14 [75756] Update bootstrap scripts
  automation/Jenkins/openvino_version.yml
  automation/bootstrap/bootstrap_os.sh
  automation/bootstrap/install_python_packages.sh
  docker/bootstrap/Dockerfile
  docker/docker-compose.local.yml
  docker/docker-compose.test.bootstrap.yml
  docker/docker-compose.yml
  requirements/requirements_bootstrap.txt
  tests/bom_test.py
Labels: CI

#36 [82511] Add license
  LICENSE
  tests/bom_test.py
Labels: SDL

#15 [81222] Building a WB image based on a clean Ubuntu
  automation/Jenkins/openvino_version.yml
  docker/dockerfiles/Dockerfile_opensource_image.template
  docker/local/build_image.sh
  requirements/requirements.txt
  tests/bom_test.py
Labels: CI, to-be-merged

#20 [80376] Adapt E2E tests for the new OMZ layout
  client/e2e/src/advanced-accuracy-configuration.e2e-spec.ts
  client/e2e/src/erase-all.e2e-spec.ts
  client/e2e/src/model-downloader.e2e-spec.ts
  client/e2e/src/pages/calibration-utils.ts
  client/e2e/src/pages/inference-utils.ts
  client/e2e/src/pages/model-download.po.ts
  client/e2e/src/pages/model-manager.po.ts
  client/e2e/src/pages/test-utils.ts
  client/e2e/src/upload-models-model-manager.e2e-spec.ts
  client/src/app/modules/model-manager/components/omz-import-ribbon-content/omz-import-ribbon-content.component.html
Labels: CI, e2e

#17 [81218] Add transformers onnx tool parser
  automation/bom/image_BOM.txt
  config/constants.py
  wb/error/code_registry.py
  wb/error/job_error.py
  wb/error/transformers_onnx_conversion_error_map.json
  wb/main/console_tool_wrapper/huggingface_model_downloader/tool.py
  wb/main/console_tool_wrapper/model_downloader/console_output_parser.py
  wb/main/console_tool_wrapper/model_optimizer/console_output_parser.py
  wb/main/huggingface_api/huggingface_api.py
  wb/main/jobs/models/import_huggingface_model_job.py
  wb/main/utils/tokenizer/tokeinzer_wrapper.py
Labels: enhancement

#25 [78161] Show fastseg models in OMZ table
  automation/bom/image_BOM.txt
  migrations/versions/9ede8e012999_enable_fastseg_models.py
  migrations/versions/c2f12b313b48_instant_assets_sharing.py
Labels: bug, to-be-merged

#39 [82042] Add TPP
  tests/bom_test.py
  third-party-programs.txt
Labels: to-be-merged, SDL

#37 [82293] Implement loading state for huggingface grid
  client/src/app/core/services/api/rest/huggingface.service.ts
  client/src/app/modules/model-manager/components/base-model-zoo-import/base-model-zoo-import.component.ts
  client/src/app/modules/model-manager/components/hugging-face-import-ribbon-content/hugging-face-import-ribbon-content.component.html
  client/src/app/modules/model-manager/components/hugging-face-import-ribbon-content/hugging-face-import-ribbon-content.component.ts
  client/src/app/modules/model-manager/components/hugging-face-import-ribbon-content/huggingface-model-details/huggingface-model-details.component.html
  client/src/app/modules/model-manager/components/hugging-face-import-ribbon-content/huggingface-model-details/huggingface-model-details.component.scss
  client/src/app/modules/model-manager/components/hugging-face-import-ribbon-content/huggingface-model-details/huggingface-model-details.component.spec.ts
  client/src/app/modules/model-manager/components/hugging-face-import-ribbon-content/huggingface-model-details/huggingface-model-details.component.ts
  client/src/app/modules/model-manager/components/model-zoo-layout/model-zoo-layout.component.html
  client/src/app/modules/model-manager/components/model-zoo-layout/model-zoo-layout.component.scss
  client/src/app/modules/model-manager/components/model-zoo-layout/model-zoo-layout.component.ts
  client/src/app/root-store/huggingface-model-store/huggingface-model-store.actions.ts
  client/src/app/root-store/huggingface-model-store/huggingface-model-store.effects.ts
  client/src/app/root-store/huggingface-model-store/huggingface-model-store.module.ts
  client/src/app/root-store/huggingface-model-store/huggingface-model-store.reducer.ts
  client/src/app/root-store/huggingface-model-store/huggingface-model-store.selectors.ts
  client/src/app/root-store/huggingface-model-store/huggingface-model-store.state.ts
  client/src/app/root-store/huggingface-model-store/index.ts
  client/src/app/root-store/root-store.module.ts
  client/src/app/root-store/state.ts
Labels: enhancement, to-be-merged

#32 [82421] Add VPU tests to the DevCloud pipeline
  client/e2e/protractor.conf.js
  client/e2e/src/pages/inference-utils.ts
  client/e2e/src/pages/target-machines.po.ts
  client/e2e/src/smoke-vpu.e2e-spec.ts
Labels: e2e, to-be-merged

#57 [83114] Update chrome driver
  client/e2e/commands.json
Labels: CI

#34 [81224] Add smoke tests for a Workbench image based on a clean Ubuntu
  automation/Jenkins/openvino_version.yml
  client/e2e/commands.json
  client/e2e/protractor.conf.js
  docker/dockerfiles/Dockerfile_opensource_image.template
  docker/local/build_image.sh
Labels: CI, to-be-merged

#44 [82726] Add E2E tests for the HF tab
  client/e2e/protractor.conf.js
  client/e2e/resources.json
  client/e2e/src/advanced-accuracy-configuration.e2e-spec.ts
  client/e2e/src/erase-all.e2e-spec.ts
  client/e2e/src/import-hugging-face-models.e2e-spec.ts
  client/e2e/src/model-downloader.e2e-spec.ts
  client/e2e/src/pages/configuration-wizard.po.ts
  client/e2e/src/pages/hugging-face-model-download.po.ts
  client/e2e/src/pages/model-download.po.ts
  client/e2e/src/pages/model-file.ts
  client/e2e/src/pages/test-utils.ts
  client/e2e/src/run-inference-cpu.e2e-spec.ts
  client/e2e/src/upload-models-model-manager.e2e-spec.ts
  client/src/app/modules/model-manager/components/hugging-face-import-ribbon-content/hugging-face-import-ribbon-content.component.html
  client/src/app/modules/model-manager/components/hugging-face-import-ribbon-content/hugging-face-import-ribbon-content.component.ts
  client/src/app/modules/model-manager/components/hugging-face-import-ribbon-content/huggingface-model-details/huggingface-model-details.component.html
  client/src/app/modules/model-manager/components/model-zoo-filter-group/model-zoo-filter/model-zoo-filter-option/model-zoo-filter-option.component.html
  client/src/app/modules/model-manager/components/model-zoo-filter-group/model-zoo-filter/model-zoo-filter.component.html
  client/src/app/modules/model-manager/components/model-zoo-filter-group/model-zoo-filters-header/model-zoo-filters-header.component.html
Labels: e2e
