Repository openvinotoolkit/workbench, pull requests merged in 2022-04, with the labels that each got.

#56 [68340] Fix Runtime references
  docs/Workbench_DG/Accuracy_Configuration.md
  docs/Workbench_DG/Deploy_and_Integrate_Performance_Criteria_into_Application.md
  docs/Workbench_DG/Deployment_Package.md
  docs/Workbench_DG/Int-8_Quantization.md
  docs/Workbench_DG/Jupyter_Notebooks.md
  docs/Workbench_DG/Key_Concepts.md
  docs/Workbench_DG/Run_Inference.md
  docs/Workbench_DG/Run_Single_Inference.md
Labels: documentation

#60 [82988] Enable GA for huggingface models
  client/src/app/app.component.ts
  client/src/app/core/services/common/google-analytics.service.ts
  client/src/app/modules/model-manager/components/hugging-face-import-ribbon-content/hugging-face-import-ribbon-content.component.ts
  client/src/app/root-store/huggingface-model-store/huggingface-model-store.actions.ts
  client/src/app/root-store/huggingface-model-store/huggingface-model-store.effects.ts
  client/src/app/root-store/huggingface-model-store/huggingface-model-store.ga.effects.ts
  client/src/app/root-store/huggingface-model-store/huggingface-model-store.module.ts
  client/src/app/root-store/model-store/model-ga.effects.ts
  client/src/app/root-store/model-store/model.actions.ts
  client/src/app/root-store/model-store/model.effects.ts
  client/tslint.json
Labels: enhancement, to-be-merged

#63 [21134] Connect markdown prettifier for OMZ models description
  client/e2e/src/pages/test-utils.ts
  client/src/app/core/services/common/link-navigation.service.ts
  client/src/app/modules/accuracy/components/advanced-accuracy-configuration/advanced-accuracy-configuration.component.scss
  client/src/app/modules/dashboard/components/deployment-manager/deployment-manager.component.scss
  client/src/app/modules/dataset-manager/components/create-dataset/create-dataset.component.spec.ts
  client/src/app/modules/dataset-manager/components/dataset-upload/dataset-upload.component.scss
  client/src/app/modules/dataset-manager/pages/import-text-dataset-page/text-dataset-data/text-dataset-data.component.spec.ts
  client/src/app/modules/dataset-manager/pages/import-text-dataset-page/text-dataset-info/text-dataset-info.component.scss
  client/src/app/modules/login/pages/login/login.component.scss
  client/src/app/modules/model-manager/components/hugging-face-import-ribbon-content/hugging-face-import-ribbon-content.component.spec.ts
  client/src/app/modules/model-manager/components/hugging-face-import-ribbon-content/huggingface-model-details/huggingface-model-details.component.html
  client/src/app/modules/model-manager/components/hugging-face-import-ribbon-content/huggingface-model-details/huggingface-model-details.component.scss
  client/src/app/modules/model-manager/components/hugging-face-import-ribbon-content/huggingface-model-details/huggingface-model-details.component.spec.ts
  client/src/app/modules/model-manager/components/hugging-face-import-ribbon-content/huggingface-model-details/huggingface-model-details.component.ts
  client/src/app/modules/model-manager/components/hugging-face-import-ribbon-content/huggingface-model-details/markdown/index.ts
  client/src/app/modules/model-manager/components/hugging-face-import-ribbon-content/huggingface-model-details/markdown/markdown.service.spec.ts
  client/src/app/modules/model-manager/components/hugging-face-import-ribbon-content/huggingface-model-details/markdown/markdown.service.ts
  client/src/app/modules/model-manager/components/model-manager-convert/model-manager-convert.component.spec.ts
  client/src/app/modules/model-manager/components/model-manager-convert/transformations-config-field/transformations-config-field.component.spec.ts
  client/src/app/modules/model-manager/components/omz-import-ribbon-content/omz-model-details/omz-model-details.component.html
  client/src/app/modules/model-manager/components/omz-model-info/omz-model-info.component.html
  client/src/app/modules/model-manager/components/omz-model-info/omz-model-info.component.spec.ts
  client/src/app/modules/target-machines/components/pipeline-stages/pipeline-stages.component.spec.ts
  client/src/app/modules/target-machines/components/pipeline-stages/stage-troubleshoot/stage-troubleshoot.component.spec.ts
  client/src/app/shared/components/dimensions-layouts/dimensions-layouts.component.spec.ts
  client/src/app/shared/components/expansion-tip/expansion-tip.component.spec.ts
  client/src/app/shared/components/info-hint/info-hint.component.spec.ts
  client/src/app/shared/components/markdown-text/markdown-elements.model.ts
  client/src/app/shared/components/markdown-text/markdown-parser.ts
  client/src/app/shared/components/markdown-text/markdown-text.component.html
  client/src/app/shared/components/markdown-text/markdown-text.component.scss
  client/src/app/shared/components/markdown-text/markdown-text.component.spec.ts
  client/src/app/shared/components/markdown-text/markdown-text.component.ts
  client/src/app/shared/components/markdown-text/markdown-text.module.ts
  client/src/app/shared/components/markdown-text/markdown.scss
  client/src/app/shared/components/markdown-text/markdown.service.ts
  client/src/app/shared/directives/external-link.directive.ts
  client/src/assets/data/hint-messages.json
  client/src/styles.scss
Labels: enhancement, includes-client

#29 [65311] Transition to Datumaro detection heuristics
  client/e2e/resources.json
  client/e2e/src/accuracy-reports.e2e-spec.ts
  client/e2e/src/gan.e2e-spec.ts
  client/e2e/src/inference-test-image.e2e-spec.ts
  client/e2e/src/int8-basic-cases.e2e-spec.ts
  client/e2e/src/model-visualization.e2e-spec.ts
  client/e2e/src/not-annotated-model-visualization.e2e-spec.ts
  client/e2e/src/parent-predictions-visualization.e2e-spec.ts
  client/e2e/src/semantic-segmentation.e2e-spec.ts
  client/e2e/src/upload-dataset.e2e-spec.ts
  config/constants.py
  docker/dockerfiles/Dockerfile
  requirements/requirements.txt
  wb/main/console_tool_wrapper/datumaro_tool/tool.py
  wb/main/dataset_utils/dataset_adapters.py
  wb/main/enumerates.py
  wb/main/jobs/datasets/convert_dataset_job.py
  wb/main/jobs/datasets/recognize_dataset_job.py
  wb/main/scripts/dataset_annotator/dataset_annotator.py
  wb/main/scripts/dataset_annotator/dataset_item_creator/base_dataset_item_creator.py
  wb/main/scripts/dataset_annotator/dataset_item_creator/classification_dataset_item_creator.py
  wb/main/scripts/dataset_annotator/dataset_item_creator/detection_dataset_item_creator.py
  wb/main/scripts/dataset_annotator/dataset_item_creator/instance_segmentation_dataset_item_creator.py
  wb/main/scripts/dataset_annotator/dataset_item_creator/segmentation_dataset_item_creator.py
  wb/main/shared/enumerates.py
  wb/utils/utils.py
Labels: CI, to-be-merged
