Repository openvinotoolkit/workbench, pull requests merged in 2022-10, with the labels that each got.

#68 [83105] Hugging Face models are marked as Generic instead of Task Classification
  .github/workflows/check-pr-name.yml
  client/src/app/modules/model-manager/components/card/card.component.ts
  client/src/app/modules/model-manager/components/hugging-face-import-ribbon-content/hugging-face-import-ribbon-content.component.html
  client/src/app/modules/model-manager/components/hugging-face-import-ribbon-content/huggingface-model-details/huggingface-model-details.component.html
  client/src/app/modules/model-manager/components/hugging-face-import-ribbon-content/huggingface-model-details/huggingface-model-details.component.scss
  client/src/app/modules/model-manager/components/hugging-face-import-ribbon-content/huggingface-model-details/huggingface-model-details.component.ts
  client/src/app/shared/models/huggingface/huggingface-model.ts
  client/src/assets/data/hint-messages.json
  wb/main/huggingface_api/huggingface_api.py
  wb/main/jobs/create_setup_bundle/create_setup_bundle_job.py
  wb/main/jobs/interfaces/job_observers.py
  wb/main/pipeline_creators/model_creation/import_huggingface_model_pipeline_creator.py
Labels: enhancement, to-be-merged

#104 Fix link to install guide
  docs/Workbench_DG/Deployment_Package.md
  docs/Workbench_DG/Setup_Remote_Target.md
Labels: to-be-merged

#69 [82812] Remove deprecated OMZ tab and components (part 1)
  .features.json
  client/e2e/src/model-import-form.e2e-spec.ts
  client/e2e/src/pages/hugging-face-model-download.po.ts
  client/e2e/src/pages/model-download.po.ts
  client/e2e/src/pages/model-file.ts
  client/e2e/src/pages/model-manager.po.ts
  client/src/app/modules/model-manager/components/base-model-zoo-import/base-model-zoo-import.component.ts
  client/src/app/modules/model-manager/components/hugging-face-import-ribbon-content/hugging-face-import-ribbon-content.component.html
  client/src/app/modules/model-manager/components/hugging-face-import-ribbon-content/hugging-face-import-ribbon-content.component.ts
  client/src/app/modules/model-manager/components/model-downloader-table/model-downloader-table.component.html
  client/src/app/modules/model-manager/components/model-downloader-table/model-downloader-table.component.scss
  client/src/app/modules/model-manager/components/model-downloader-table/model-downloader-table.component.spec.ts
  client/src/app/modules/model-manager/components/model-downloader-table/model-downloader-table.component.ts
  client/src/app/modules/model-manager/components/model-downloader-table/model-downloader.service.spec.ts
  client/src/app/modules/model-manager/components/model-downloader-table/model-downloader.service.ts
  client/src/app/modules/model-manager/components/model-manager-import/model-manager-import.component.html
  client/src/app/modules/model-manager/components/model-manager-import/model-manager-import.component.scss
  client/src/app/modules/model-manager/components/model-manager-import/model-manager-import.component.spec.ts
  client/src/app/modules/model-manager/components/model-manager-import/model-manager-import.component.ts
  client/src/app/modules/model-manager/components/model-manager-wizard/model-manager-wizard.component.html
  client/src/app/modules/model-manager/components/model-manager-wizard/model-manager-wizard.component.spec.ts
  client/src/app/modules/model-manager/components/model-manager-wizard/model-manager-wizard.component.ts
  client/src/app/modules/model-manager/components/model-zoo-layout/model-zoo-content/model-zoo-content.component.html
  client/src/app/modules/model-manager/components/model-zoo-layout/model-zoo-content/model-zoo-content.component.ts
  client/src/app/modules/model-manager/components/omz-import-ribbon-content/omz-import-ribbon-content.component.html
  client/src/app/modules/model-manager/components/omz-import-ribbon-content/omz-import-ribbon-content.component.ts
  client/src/app/modules/model-manager/components/omz-model-info/omz-model-info.component.html
  client/src/app/modules/model-manager/components/omz-model-info/omz-model-info.component.scss
  client/src/app/modules/model-manager/components/omz-model-info/omz-model-info.component.spec.ts
  client/src/app/modules/model-manager/components/omz-model-info/omz-model-info.component.ts
  client/src/app/modules/model-manager/model-manager.module.ts
  client/src/app/root-store/globals-store/globals.state.ts
  client/src/app/root-store/model-store/model.actions.ts
  client/src/app/root-store/model-store/model.reducer.ts
  client/src/assets/data/hint-messages.json
  wb/main/enabled_features_service.py
Labels: enhancement, includes-client, to-be-merged, manual-validation-requested

#45 [75807] Inference results visualization. Make colors of bounding boxes explicitly contrast to each other
  client/e2e/protractor.conf.js
  client/e2e/resources.json
  client/e2e/src/model-visualization.e2e-spec.ts
  client/e2e/src/not-annotated-model-visualization.e2e-spec.ts
  client/e2e/src/pages/inference-test-image.po.ts
  client/e2e/src/pages/test-utils.ts
  client/src/app/modules/accuracy/color-coding.service.ts
  client/src/app/modules/accuracy/components/visualization/network-output/image-renderer/image-renderer.component.ts
  client/src/app/modules/accuracy/components/visualization/network-output/image-renderer/image-renderer.ts
  client/src/app/modules/accuracy/components/visualization/network-output/image-renderer/lib/box.ts
  client/src/app/modules/accuracy/components/visualization/network-output/image-renderer/lib/coordinates-helper.ts
  client/src/app/modules/accuracy/components/visualization/network-output/image-renderer/lib/index.ts
  client/src/app/modules/accuracy/components/visualization/network-output/image-renderer/lib/polygon.ts
  client/src/app/modules/accuracy/components/visualization/network-output/image-renderer/lib/shapes.ts
  client/src/app/modules/accuracy/components/visualization/network-output/image-renderer/painting-canvas/box-painter.ts
Labels: enhancement, to-be-merged

#111 [92953] Fix building image from opensource
  docker/local/build_image.sh
Labels: CI

#49 [82939] Advanced HF models filter
  automation/bom/image_BOM.txt
  client/e2e/src/int8-advanced-cases.e2e-spec.ts
  client/src/assets/data/hint-messages.json
  requirements/requirements.txt
  wb/error/job_error.py
  wb/error/transformers_onnx_conversion_error_map.json
  wb/main/console_tool_wrapper/environment_managment_tool/tool.py
  wb/main/environment/creator/manifest_specific_environment_creator.py
  wb/main/environment/creator/unified_environment_creator.py
  wb/main/huggingface_api/huggingface_api.py
  wb/main/huggingface_api/validators.py
  wb/main/jobs/models/import_huggingface_model_job.py
Labels: enhancement, to-be-merged, manual-validation-accepted
