Repository openvinotoolkit/workbench, pull requests merged in 2023-01, with the labels that each got.

#136 [87780] Fix link to POT in docs
  docs/Workbench_DG/Export_Project.md
  docs/Workbench_DG/Overview.md
Labels: documentation, to-be-merged

#134 [100271] Remove OPENCV mentioning from deployment-related jobs
  client/package-lock.json
  docker/local/build_image.sh
  docker/remote_execution_docker/Dockerfile
  wb/main/enumerates.py
  wb/main/utils/bundle_creator/bundle_downloader.py
Labels: bug, to-be-merged

#138 [76862] Bump OV package to 22.3, update sample
  docker/dockerfiles/Dockerfile
  docker/dockerfiles/Dockerfile_opensource_image.template
  tutorials/sample_application/main.cpp
  tutorials/sample_application/tutorial_sample_application.ipynb
Labels: dependencies

#139 [101367] [DOCS] Delete myriad and hddl from docs
  docs/Workbench_DG/Select_Environment.md
  docs/Workbench_DG/Visualize_Model.md
Labels: documentation

#135 [76862] [101797] Unskip deployment tests with clean Ubuntu
  client/e2e/src/deployment-manager.e2e-spec.ts
  client/e2e/src/pages/packaging.po.ts
  client/e2e/src/pages/test-utils.ts
  client/src/app/modules/dashboard/components/deployment-manager/deployment-manager.component.ts
  docker/local/build_image.sh
  tests/deployment_tests/Dockerfile
  tests/deployment_tests/ie_sample/CMakeLists.txt
  tests/deployment_tests/ie_sample/main.cpp
  tests/deployment_tests/scripts/copy_and_make_sample.sh
  tests/deployment_tests/scripts/execute_sample.sh
  tests/deployment_tests/scripts/get_bundle.py
  wb/main/enumerates.py
Labels: CI

#140 [65499] Return models to OMZ model list & Remove aclnet-int8
  client/package-lock.json
  wb/main/console_tool_wrapper/model_downloader/utils.py
Labels: bug
